---
- hosts: k8s
  remote_user: root
  gather_facts: True
  tasks:
  - name: remove nodes kubectl
    yum:
     name: 'kubectl'
     state: 'absent'
    when: ansible_default_ipv4["address"] != "192.168.50.204"
  - name: install kubelet kubeadm
    yum: 
     name: '{{item}}'
     state: 'present'
    loop:
     - 'kubelet-1.15.2'
     - 'kubeadm-1.15.2'
    loop_control:
     pause: 10
     index_var: my_idx
  - name: install master kubectl
    yum:
     name: 'kubectl-1.15.2'
     state: 'present'
    when: ansible_default_ipv4["address"] == "192.168.50.204"
  - name: upgrade k8s-master
    shell: "echo yes | kubeadm upgrade apply v1.15.2"
    when: ansible_default_ipv4["address"] == "192.168.50.204"
  - name: upgrade k8s-nodes
    shell: "echo yes | kubeadm upgrade node"
    when: ansible_default_ipv4["address"] != "192.168.50.204"
  - name: restart k8s_cluster kubelet
    shell: "systemctl daemon-reload && systemctl restart kubelet"
